### ISSUE TITLE
Can't Get Full Performance of Triple-SSD RAID-0 Array

### ISSUE THREAD

**Issue by FluorescentGreen5** [maharmstone/winmd#8]
While Dynamic Disks lets me achieve around 1.2 GB/s on 3 SSDs running in RAID-0, WinMD can only achieve 825 MB/s, akin to only 2 SSDs in RAID-0. CPU usage is around 4% during sequential tests in CrystalDiskMark and each SSD only gets to about 66% usage in Task Manager during these tests. The SSDs only reach 100% during random access tests.

CPU: AMD Ryzen 5 3600
RAM: 2x8GB DDR4-3200
SSDs: 480 GB Intel DC S3610

**UPDATE:** It seems like the [MadMax plotter](https://github.com/madMAx43v3r/chia-plotter) is able to break 1 GB/s when plotting to the array.

**Comment by maharmstone** [comment]
Interesting. I can't think off the top of my head why this would be - I'll look into it when I get the chance...

**Comment by vdavide** [comment]
@maharmstone will you ever update this very promising project? At least degraded mount and resync

**Comment by maharmstone** [comment]
Plan to, just been busy with other things!

**Comment by FluorescentGreen5** [comment]
I think I found the issue: CrystalDiskMark sometimes only uses 1 thread for both it's sequential tests. I will try manually configuring it to use all 12 threads when I get the time.

**Comment by FluorescentGreen5** [comment]
Yep, that seems to have done the trick.
![image](https://user-images.githubusercontent.com/37255338/144389139-e82f6b39-3794-4232-8e57-bc8238161dfb.png)
